alilleybrinker/langs-in-rust

README.md

Add rust-prolog which is a port of SML miniprolog

add rust-prolog

---

README.md

Don't forget to star my project if you think it of good use :)

Add Pr47 to the list

---

README.md

My favorite review: "This is useless and awesome!" - [u/Ball-Blam-Burglerber](https://www.reddit.com/r/StarWars/comments/r056of/comment/hlsxc8m/?utm_source=share&utm_medium=web2x&context=3)

Add "The Force"

---

README.md

You asked to add Sligh to this list on lobste.rs. Here's a PR for that!

Add sligh to language list

---

README.md
languages.json
update.py

This adds:
- Jakt
- Foolang
- Chili
- Tethys
- Calypso
- Butter
- Sphinx
And also updates all the counts.

Add a bunch more languages.

---

README.md
languages.json
update.py

`update.py` had a bug where it would produce inconsistent results, which is fixed in the first commit. The second commit adds Inko back to the list of languages, without updating the other ones (to keep the diff small).

Fix updating the list of languages, and add Inko back to the list

---

README.md
languages.json

Hi,
Recently I built a programming language called [Boson](https://github.com/Narasimha1997/boson-lang). Felt it would be a nice add to this list as people can find it and use it as a reference if they are building/learning how programming languages are built and work. 
Thanks

Add boson programming language to the list

---

README.md
languages.json

I run update.py to add my langage in the list, readme is update now

run update.py

---

README.md
languages.json

Nushell is a new shell where you can write bash-like pipelines with Rust interop.

added nushell

---

README.md

Add Duckscript

---

README.md

Add Loxcraft

---

README.md

Add Ry programming language

---

README.md

Add Terbium

---

README.md
languages.json

[Move](https://github.com/move-language/move) is a programming language for writing safe smart contracts originally developed at Facebook to power the Diem blockchain.
This pull request adds this language to the list.

Added Move programming language to the list

---

README.md
languages.json

Restore Nushell using GitHub URL so it sticks around

---

README.md
languages.json

My github username has changed!

Update repository URL for Wright

---

README.md
languages.json

Adding RayQL - A Schema and Query Language written in Rust.

add: RayQL

---

README.md
languages.json

This is a high level language designed to compile to Brainfuck, the compiler for which is written in Rust.
[GitHub](https://github.com/Heathcorp/Mastermind)
[Online IDE](https://mastermind.lostpixels.org)

Add Mastermind language.

---

README.md
languages.json

Add Cyrus Lang

---

README.md
languages.json

Hello! I am the author of the Watt programming language. It will be nice to see my language in this list. Thanks!

Add Watt language
